server:
  port: 5001

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:user
      username: sa
      password:

  application:
    name: user-service
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 762528943573-psakgl9g8ij4gnqsm08avi9k9gj725h1.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: hello user service

jwt:
  secret: this_is_secret